name: Trivy Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  install-trivy:
    name: ♻️ Install Trivy
    runs-on: ubuntu-latest
    outputs:
      trivy-path: ${{ steps.set-output.outputs.path }}
    steps:
      - name: 🚀 Install Trivy
        id: set-output
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          echo "path=/usr/local/bin/trivy" >> $GITHUB_OUTPUT

  scan-dependencies:
    name: 📦 Dependency Vulnerability Scan
    needs: install-trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy File System Scan
        run: |
          echo "🔍 Scanning project dependencies..."
          trivy fs --exit-code 1 --severity HIGH,CRITICAL .

  scan-docker:
    name: 🐳 Docker Image Scan
    needs: install-trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for Dockerfile
        id: check
        run: |
          if [ -f Dockerfile ]; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Docker (for buildx)
        if: steps.check.outputs.found == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        if: steps.check.outputs.found == 'true'
        run: docker build -t thechesswire-app .

      - name: Run Trivy Image Scan
        if: steps.check.outputs.found == 'true'
        run: |
          echo "🐳 Scanning Docker image thechesswire-app..."
          trivy image --exit-code 1 --severity HIGH,CRITICAL thechesswire-app
