name: Trivy Vulnerability Scanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 1' # Weekly scan on Mondays at 03:00 UTC

permissions:
  contents: read

jobs:
  trivy:
    name: Run Trivy Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          format: table
          exit-code: 1 # 🔥 This will fail the workflow if vulnerabilities are found
          output: trivy-results.txt

      - name: Upload Trivy scan report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-results.txt
